language: go
before_install:
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
- terraform -v
install: true
env:
  global:
  - tf_version=1.15.0
stages:
- test
jobs:
  include:
  - stage: test
    if: type = pull_request AND branch != master
    go: 1.16.x
    script: go test ./... -v -short
  - if: "(branch = master) OR (tag IS present)"
    go: 1.16.x
    script: go test ./... -v -short